export enum QuestionTypes {
    CHECK_LIST_MULTI_SELECTION = 1,
    INPUT_TEXT_NUMBER = 2,
    COMBO_SELECTION = 3,
    MESSAGE = 4,
    LIST_SINGLE_SELECTION = 5,
    INPUT_SINGLE = 6,
    INPUT_LONG_TEXT =7,
    INPUT_MULTI = 8,
    LIST_ACCORDION = 9
}